### ISSUE TITLE
一处没必要翻译的内容

### ISSUE THREAD

**Issue by lychichem** [shuax/EdgeChinese#1]
三个点的菜单里，“历史记录→清除浏览数据”后面的快捷键，delete没必要翻译成删除（个人意见），建议把这里改回原本的delete

**Comment by shuax** [comment]
![image](https://user-images.githubusercontent.com/6940583/55299353-3f2f3800-5465-11e9-8b84-37671ed6dc24.png)
这个可能没有办法，我实际上是翻译的这个位置的delete，可能有一些语言包是共用的。
