### ISSUE TITLE
设置-语言和翻译UI中重复的简体标注

### ISSUE THREAD

**Issue by lychichem** [shuax/EdgeChinese#11]
![image](https://user-images.githubusercontent.com/9316590/57929385-c0437100-78e5-11e9-9f3e-aee29852027a.png)
翻译UI（就是在flag里启用了translate之后访问外文网页会在地址栏弹出的那个）也有一样的问题，不知道是哪个字串用的范围太广了。

**Comment by shuax** [comment]
这个中文简体并非语言包中的数据。最新金丝雀应该已经修复了。
![image](https://user-images.githubusercontent.com/6940583/57962918-d423bd00-794f-11e9-8bf5-e8d3fdbc1bd4.png)
![image](https://user-images.githubusercontent.com/6940583/57962919-d8e87100-794f-11e9-9caa-d9e978ec4f45.png)

**Comment by lychichem** [comment]
那看来是现在这个dev的bug，我等下周更新修复好了
