### ISSUE TITLE
大神速度可真快呀

### ISSUE THREAD

**Issue by Disappear94** [shuax/EdgeChinese#3]
但是124错位很多。。。我还在尝试自己生成，结果就刷出更新了，但是好像没法到能用的程度、

**Comment by Disappear94** [comment]
我自己生成好的没有问题哈哈

**Comment by shuax** [comment]
如果要生成一个特定版本的资源。

1、放入这个版本的en-us.pak
2、运行unpack.bat解包en-us.pak为en-us.json
3、运行translate.py把en-us.json汉化为zh-CN.json
4、运行build.bat把zh-CN.json打包成zh-CN.pak

放回zh-CN.pak即可得到汉化版。
