### ISSUE TITLE
请求做GreenEdge

### ISSUE THREAD

**Issue by gg201904** [shuax/EdgeChinese#5]
请求做GreenEdge，谢谢

**Comment by shuax** [comment]
https://github.com/shuax/EdgeChinese/releases
打好的包里面已经集成了Edge++增强软件。

**Comment by Disappear94** [comment]
> https://github.com/shuax/EdgeChinese/releases
> 打好的包里面已经集成了Edge++增强软件。

可是现在打不开了也。。。是不是要上pcbeta下那个打包好的里面就有

**Comment by shuax** [comment]
https://tools.shuax.com/edge/
