### ISSUE TITLE
edge://downloads/内汉化无效

### ISSUE THREAD

**Issue by Disappear94** [shuax/EdgeChinese#6]
已经在manual.json中添加了相关翻译信息，但是该页面下的汉化依旧无法显示，难道该部分不读取pak语言文件夹中的内容？
![QQ截图20190413104900](https://user-images.githubusercontent.com/47406419/56073620-e3a46900-5dd9-11e9-94b3-b90587baaf85.png)
![QQ截图20190413104914](https://user-images.githubusercontent.com/47406419/56073621-e3a46900-5dd9-11e9-807a-3de623796d76.png)

**Comment by shuax** [comment]
有部分内容不在语言包里，而是写死在resources.pak了。

**Comment by Disappear94** [comment]
> 有部分内容不在语言包里，而是写死在resources.pak了。

原来是这样，试了试解开resource看看，发现这东西有点大。。。遂放弃，还是等微软官方搞吧。反正目前除了这个也没有什么地方碍眼了。
话说如何贡献manual.json？
直接发issue里后大神手动添加进去？（没用过GitHub，也不会fork或者pullrequest。。。

`    "Others":"其它",
    "Save link as": "链接另存为",
    "Copy link": "复制链接地址",
    "All files": "所有文件",
    "PDFs": "PDF文件",
    "Documents": "文档",
    "Apps": "应用",
    "Images": "图片",
    "Compressed files": "压缩文件",
    "Videos": "视频",
    "Audio": "音频",
    "Others": "其他",
    "Downloads": "下载",
    "Settings": "设置",
    "Addresses, phone numbers, and more": "地址，号码和其他信息",
    "Manage profile settings": "管理您的配置",
    "Go to my account": "转到我的账户",
    "Sync settings": "同步设置",
    "Open file": "打开文件",`

**Comment by shuax** [comment]
我觉得汉化差不多就这样了，做到100%完美的时候，官方都出中文了，没有多大意义。

**Comment by Disappear94** [comment]
> 我觉得汉化差不多就这样了，做到100%完美的时候，官方都出中文了，没有多大意义。

也对，目之所及能基本覆盖也就够了~
