### ISSUE TITLE
pak_tools能不能搞个mac的命令行版本的

### ISSUE THREAD

**Issue by yhl452493373** [shuax/EdgeChinese#9]
昨天微软出了mac版的，用现在的工具需要在windows平台上搞，然后放回mac测试。麻烦的很。

**Comment by shuax** [comment]
python在哪里都能跑啊。pak_tools是我用golang写的，也可以编译mac版。
https://github.com/shuax/ChromePAK-V5

**Comment by yhl452493373** [comment]
好的好的，3Q
